# Generated by Django 2.0.6 on 2018-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortly',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_target', models.URLField(max_length=250)),
                ('click_count', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Urls',
                'verbose_name': 'Url',
            },
        ),
    ]
