# Generated by Django 2.0.6 on 2018-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortly',
            name='url_target',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
