# Generated by Django 2.0.7 on 2018-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0002_auto_20180610_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortly',
            name='click_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
